# Generated by Django 5.0 on 2024-01-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
    ]
