# Generated by Django 5.0 on 2024-01-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_member_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membernew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
