# Generated by Django 5.0 on 2024-01-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_membernew_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='membernew',
            name='rollno',
            field=models.IntegerField(null=True),
        ),
    ]
