# Generated by Django 5.0 on 2024-01-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_membernew_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='membernew',
            name='phoneno',
            field=models.IntegerField(null=True),
        ),
    ]
