# Generated by Django 5.0 on 2024-01-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_membernew_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='membernew',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='member_photo/'),
        ),
    ]
